<?php

/**
 * @file
 */

use Drupal\Core\Entity\ContentEntityType;

/**
 * Implements hook_views_data().
 */
function pagedesigner_block_adaptable_views_data() {
  $data = [];
  $definition = [
    'title' => t('Entity pagedesigner filter'),
    'filter' => [
      'title' => t('Entity pagedesigner filter'),
      'field' => 'id',
      'id' => 'pba_entity_filter',
    ],
  ];
  $entityTypes = \Drupal::entityTypeManager()->getDefinitions();
  foreach ($entityTypes as $type) {
    $type = \Drupal::entityTypeManager()->getDefinition($type->id());
    if ($type instanceof ContentEntityType && !empty($type->getDataTable())) {
      $data[$type->getDataTable()]['pba_entity_filter'] = $definition;
      $data[$type->getDataTable()]['pba_entity_filter']['entity field'] = $type->getKey('id');
    }
  }
  return $data;
}
